=== raml-apis/EwayRapid/schemas/refundTransaction-schema.json
{
    "type": "object",
    "$schema": "http://json-schema.org/draft-03/schema",
    "required": false,
    "properties": {
        "CustomerIP": {
            "type": "string",
            "maxLength": 50,
            "required": false
        },
        "Customer": {
            "type": "object",
            "required": false,
            "properties": {
                "CardDetails": {
                    "type": "object",
                    "required": false,
                    "properties": {
                        "ExpiryMonth": {
                            "type": "string",
                            "maxLength": 2,
                            "required": false
                        },
                        "ExpiryYear": {
                            "type": "string",                            
                            "maxLength": 2,
                            "required": false
                        }
                    }
                },
                "City": {
                    "type": "string",
                    "maxLength": 50,
                    "required": false
                },
                "Comments": {
                    "type": "string",
                    "maxLength": 255,
                    "required": false
                },
                "CompanyName": {
                    "type": "string",
                    "maxLength": 50,
                    "required": false
                },
                "Country": {
                    "type": "string",
                    "maxLength": 2,
                    "required": false
                },
                "Email": {
                    "type": "string",
                    "maxLength": 50,
                    "required": false
                },
                "Fax": {
                    "type": "string",
                    "maxLength": 32,
                    "required": false
                },
                "FirstName": {
                    "type": "string",
                    "maxLength": 50,
                    "required": false
                },
                "JobDescription": {
                    "type": "string",
                    "maxLength": 50,
                    "required": false
                },
                "LastName": {
                    "type": "string",
                    "maxLength": 50,
                    "required": false
                },
                "Mobile": {
                    "type": "string",
                    "maxLength": 32,
                    "required": false
                },
                "Phone": {
                    "type": "string",
                    "maxLength": 32,
                    "required": false
                },
                "PostalCode": {
                    "type": "string",
                    "maxLength": 30,
                    "required": false
                },
                "Reference": {
                    "type": "string",
                    "maxLength": 50,
                    "required": false
                },
                "State": {
                    "type": "string",
                    "maxLength": 50,
                    "required": false
                },
                "Street1": {
                    "type": "string",
                    "maxLength": 50,
                    "required": false
                },
                "Street2": {
                    "type": "string",
                    "maxLength": 50,
                    "required": false
                },
                "Title": {
                    "type": "string",
                    "maxLength": 5,
                    "required": false
                },
                "Url": {
                    "type": "string",
                    "maxLength": 512,
                    "required": false
                }
            }
        },
        "DeviceID": {
            "type": "string",
            "maxLength": 50,
            "required": false
        },
        "Items": {
            "type": "array",
            "required": false,
            "items": {
                "type": "object",
                "required": false,
                "properties": {
                    "Description": {
                        "type": "string",
                        "maxLength": 26,
                        "required": false
                    },
                    "Quantity": {
                        "type": "string",
                        "maxLength": 6,
                        "required": false
                    },
                    "SKU": {
                        "type": "string",
                        "maxLength": 12,
                        "required": false
                    },
                    "Tax": {
                        "type": "string",
                        "maxLength": 8,
                        "required": false
                    },
                    "Total": {
                        "type": "string",
                        "maxLength": 8,
                        "required": false
                    },
                    "UnitCost": {
                        "type": "string",
                        "maxLength": 8,
                        "required": false
                    }
                }
            }
        },
        "Options": {
            "type": "array",
            "required": false,
            "items": {
                "type": "object",
                "required": false,
                "properties": {
                    "Value": {
                        "type": "string",
                        "maxLength": 254,
                        "required": false
                    }
                }
            }
        },
        "PartnerID": {
            "type": "string",
            "maxLength": 50,
            "required": false
        },
        "Refund": {
            "type": "object",
            "required": false,
            "properties": {
                "CurrencyCode": {
                    "type": "string",
                    "maxLength": 3,
                    "required": false
                },
                "InvoiceDescription": {
                    "type": "string",
                    "maxLength": 64,
                    "required": false
                },
                "InvoiceNumber": {
                    "type": "string",
                    "maxLength": 16,
                    "required": false
                },
                "InvoiceReference": {
                    "type": "string",
                    "maxLength": 50,
                    "required": false
                },
                "TotalAmount": {
                    "type": "number"
                },
                "TransactionID": {
                    "type": "string",
                    "maxLength": 8
                }
            }
        },
        "ShippingAddress": {
            "type": "object",
            "required": false,
            "properties": {
                "City": {
                    "type": "string",
                    "maxLength": 50,
                    "required": false
                },
                "Country": {
                    "type": "string",
                    "maxLength": 2,
                    "required": false
                },
                "FirstName": {
                    "type": "string",
                    "maxLength": 50,
                    "required": false
                },
                "LastName": {
                    "type": "string",
                    "maxLength": 50,
                    "required": false
                },
                "Phone": {
                    "type": "string",
                    "required": false
                },
                "PostalCode": {
                    "type": "string",
                    "maxLength": 30,
                    "required": false
                },
                "ShippingMethod": {
                    "enum": [
                        "Unknown",
                        "LowCost",
                        "DesignatedByCustomer",
                        "International",
                        "Military",
                        "NextDay",
                        "StorePickup",
                        "TwoDayService",
                        "ThreeDayService",
                        "Other"
                    ],
                    "required": false
                },
                "State": {
                    "type": "string",
                    "maxLength": 50,
                    "required": false
                },
                "Street1": {
                    "type": "string",
                    "maxLength": 50,
                    "required": false
                },
                "Street2": {
                    "type": "string",
                    "maxLength": 50,
                    "required": false
                },
                "Email": {
                    "type": "string",
                    "maxLength": 50,
                    "required": false
                },
                "Phone": {
                    "type": "string",
                    "maxLength": 32,
                    "required": false
                },
                "Fax": {
                    "type": "string",
                    "maxLength": 32,
                    "required": false
                }
            }
        }
    }
}

=== raml-apis/EwayRapid/examples/refundTransaction-example.json
{
    "Refund": {
        "TotalAmount": 100,
        "InvoiceNumber": "Inv 21540",
        "InvoiceDescription": "Individual Invoice Description",
        "InvoiceReference": "513456",
        "CurrencyCode": "AUD",
        "TransactionID": "123456789"
    },
    "Customer": {
        "Reference": "A12345",
        "Title": "Mr.",
        "FirstName": "John",
        "LastName": "Smith",
        "CompanyName": "Demo Shop 123",
        "JobDescription": "Developer",
        "Street1": "Level 5",
        "Street2": "369 Queen Street",
        "City": "Auckland",
        "State": "",
        "PostalCode": "1010",
        "Country": "au",
        "Email": "",
        "Phone": "09 889 0986",
        "Mobile": "09 889 0986",
        "Comments": "",
        "Fax": "",
        "Url": "",
        "CardDetails": {
            "ExpiryMonth": "12",
            "ExpiryYear": "16"
        }
    },
    "ShippingAddress": {
        "ShippingMethod": "NextDay",
        "FirstName": "John",
        "LastName": "Smith",
        "Street1": "Level 5",
        "Street2": "369 Queen Street",
        "City": "Auckland",
        "State": "",
        "Country": "nz",
        "PostalCode": "1010",
        "Phone": "09 889 0986"
    },
    "Items": [
        {
            "SKU": "SKU1",
            "Description": "Description1",
            "Quantity": "1",
            "UnitCost": "1",
            "Tax": "0",
            "Total": "1"
        }
    ],
    "Options": [
        {
            "Value": "Option1"
        },
        {
            "Value": "Option2"
        },
        {
            "Value": "Option3"
        }
    ],
    "DeviceID": "D1234",
    "CustomerIP": "127.0.0.1",
    "PartnerID": "04A0FD665F7348A295C5B9EE95400301"
}
